services:
  api: 
    build: ./pagamentoSimples
    networks:
      - pagamento
    ports:
      - 8080:8080
    environment:
      - SPRING.JPA.HIBERNATE.DDL-AUTO=update
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.URL=jdbc:mysql://mysql:3306/payment
      - SPRING.DATASOURCE.PASSWORD=123
      - SPRING.DATASOURCE.DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
    restart: always
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.33
    environment:
      - MYSQL_DATABASE=payment
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - 3305:3306
    networks:
      - pagamento
networks:
  pagamento:
    driver: bridge
    